apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  promotionTemplate:
    spec:
      appRef:
        kind: Application
        name: kargo-helm-dev
        namespace: argocd
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/dev
            - name: argocdApp
              value: kargo-helm-dev
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: true
    - origin:
        kind: Warehouse
        name: features
      sources:
        direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - dev
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      appRef:
        kind: Application
        name: kargo-helm-staging
        namespace: argocd
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/staging
            - name: argocdApp
              value: kargo-helm-staging
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      appRef:
        kind: Application
        name: kargo-helm-prod
        namespace: argocd
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
