apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-helm
spec:
  subscriptions:
  - image:
      repoURL: us-east4-docker.pkg.dev/sap-ems-gap-sandbox/ghcr/icarusdes/guestbook
      imageSelectionStrategy: SemVer

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/cesarnog/kargo-helm.git
      includePaths:
      - base/feature-flags.yaml
